# ==============================================================================
# RSS v0.1.0 Kernel Runtime
# Module: Acceptance Test Runner
# Copyright (c) 2025-2026 Christian Robert Rose
#
# DUAL-LICENSE NOTICE:
# This software is released under a Dual-License model.
#
# 1. GNU Affero General Public License v3.0 (AGPLv3)
#    You may use, distribute, and modify this code under the terms of the AGPLv3.
#    If you modify or distribute this software, or integrate it into your own
#    project, your entire project must also be open-sourced under the AGPLv3.
#    Network use is distribution: if you run a modified version of this software
#    on a server and allow users to interact with it remotely, you must make the
#    complete corresponding source code available to those users under AGPLv3.
#
# 2. Commercial / Contractor License Exception
#    If you wish to use this software in a closed-source, proprietary, or
#    commercial environment (including SaaS or network-accessible deployments)
#    without adhering to the AGPLv3 open-source requirements, you must obtain
#    a separate Contractor License from the author.
#
# Contact: rose.systems@outlook.com  (Subject: "Contact Us ? RSS Commercial License")
# ==============================================================================
"""Canonical acceptance runner for RSS v0.1.0.

The proof bodies live in smaller domain test modules. This file remains the
one-command acceptance surface: `python tests/test_all.py`.
"""
import test_support as _support

from test_core_runtime import (
    test_constitution,
    test_constitution_load_constitution,
    test_state_machine,
    test_genesis_blocking,
    test_llm,
    test_runtime,
    test_pre_seal_drift_check,
    test_write_ahead_guarantee,
    test_config_driven_verbs,
    test_pipeline_stage_tracking,
    test_safe_stop_inflight,
    test_configurable_llm_timeout,
    test_llm_response_validation,
    test_ward_hook_enforcement,
    test_runtime_default_term_pack_is_config_driven,
    test_clear_safe_stop_idempotence,
    test_llm_availability_timeout_is_config_driven,
)

from test_governance_seats import (
    test_ward,
    test_scope,
    test_meaning_law,
    test_execution_word_boundary_hardening,
    test_scribe,
    test_scribe_extended_edges,
    test_seal,
    test_oath,
    test_cycle,
    test_cycle_extended_edges,
    test_vocabulary_management,
    test_word_boundary,
    test_classification_order,
    test_anti_trojan,
    test_anti_trojan_runtime,
    test_synonym_removal,
    test_compound_detection,
    test_contextual_reinjection,
    test_redline_suppression,
    test_seal_review_attestation,
    test_s7_amendment_ceremony,
    test_oath_extended_edges,
    test_oath_input_normalization_and_handle_edges,
    test_oath_additional_proof,
    test_seal_extended_edges,
    test_seal_ceremony_additional_proof,
    test_s7_amendment_persistence_roundtrip,
)

from test_hubs_persistence import (
    test_hubs,
    test_pav,
    test_persistence,
    test_persistence_roundtrip,
    test_s0_8_4_governed_state_bootstrap_roundtrip,
    test_s4_personal_scope_guard,
    test_s4_scope_immutability,
    test_s4_scope_hub_validation,
    test_s4_scope_container_id,
    test_s4_archival_original_hub,
    test_s4_hard_purge,
    test_s4_governed_search,
    test_s4_ledger_pav_exclusion,
    test_s4_redline_declassification,
    test_s4_pav_hub_audit,
    test_s4_persistence_roundtrip,
    test_s4_hub_provenance,
    test_s4_provenance_persistence,
    test_s4_pipeline_integration,
    test_f2_entry_id_stability,
    test_f2_container_entry_id_stability,
    test_a1_consent_persistence_roundtrip,
    test_archive_entry_returns_hub_entry,
)

from test_tenant_containers import (
    test_tecton,
    test_s5_sigil_alignment,
    test_s5_lifecycle_transitions,
    test_s5_destroyed_inaccessibility,
    test_s5_profile_immutability,
    test_s5_trace_filtering,
    test_s5_lifecycle_logging,
    test_s5_lifecycle_provenance,
    test_s5_scope_policy_tuples,
    test_s5_can_call_advisors,
    test_s5_container_persistence,
    test_s5_container_isolation,
    test_s5_s4_rules_in_containers,
    test_s5_valid_transitions_table,
    test_s5_consent_scoping,
    test_phase_e5_contextvar_isolation,
    test_phase_d_regression_battery,
    test_tecton_destructive_transitions_require_reason,
)

from test_audit_trace import (
    test_audit_log,
    test_trace_export,
    test_safe_stop_persistent,
    test_trace_seat,
    test_event_code_taxonomy,
    test_f4_event_code_registry,
    test_f4_event_categorization,
    test_f4_export_includes_summary,
    test_s6_schema_version_tracking,
    test_s6_schema_migrated_event,
    test_s6_chain_hash_migration_scaffold,
    test_s6_boot_chain_verification,
    test_s6_boot_chain_detects_tampering,
    test_s6_event_codes_registered,
    test_s6_bootstrap_event_sequence,
    test_s6_cold_verifier,
    test_a1_historical_trace_chain_loaded_on_restart,
    test_a1_boot_verification_catches_persisted_tamper,
    test_a1_unified_container_filter,
    test_a1_export_from_db_emits_chain_valid,
    test_a1_ttl_enforcement_in_stage_4,
    test_a1_post_llm_scan_covers_archive_and_ledger,
    test_probe_chain_catches_duplicate_content_tamper,
    test_probe_hash_envelope_version_marker_present,
    test_probe_container_filter_prefix_boundary,
    test_probe_safe_stop_recovery_ceremony,
    test_trace_export_cold_container_redline_sanitization,
    test_trace_export_extended_edges,
    test_trace_export_token_boundary_sanitization,
    test_trace_verify_cli_error_classification,
    test_trace_verify_registry_load_failure_is_nonfatal,
    test_trace_verify_additional_proof,
    test_trace_verify_human_report_branches,
    test_trace_export_additional_proof,
)

from test_adversarial_scenarios import (
    test_adversarial_ingress,
    test_adversarial_cross_container,
    test_adversarial_scope_escalation,
    test_adversarial_audit_tamper,
    test_adversarial_malformed_inputs,
    test_adversarial_policy_confusion,
    test_domain_pack_equivalence,
    test_exception_context_leak,
    test_idempotence_replay,
    test_instructional_override,
    test_scenario_high_liability_flow,
    test_scenario_tamper_recovery,
    test_phase_e_regression_battery,
    test_c_phase_regression_battery,
    test_probe_redline_not_leaked_via_search_surfaces,
    test_probe_rune_resists_normalization_bypass,
    test_probe_pav_still_excludes_redline_via_list_hub,
    test_probe_indirect_prompt_injection_stays_data_not_authority,
    test_probe_untrusted_import_hash_binding,
)

from test_demo_reference_pack import (
    test_genesis_binding_and_offline_fallback,
    test_demo_world_seed_and_container_isolation,
    test_phase_g_demo_suite_operator_flow,
)

TESTS = [
    test_constitution,
    test_constitution_load_constitution,
    test_audit_log,
    test_ward,
    test_scope,
    test_hubs,
    test_pav,
    test_meaning_law,
    test_state_machine,
    test_execution_word_boundary_hardening,
    test_scribe,
    test_scribe_extended_edges,
    test_seal,
    test_oath,
    test_cycle,
    test_cycle_extended_edges,
    test_persistence,
    test_persistence_roundtrip,
    test_s0_8_4_governed_state_bootstrap_roundtrip,
    test_vocabulary_management,
    test_trace_export,
    test_safe_stop_persistent,
    test_genesis_blocking,
    test_llm,
    test_runtime,
    test_tecton,
    test_trace_seat,
    test_pre_seal_drift_check,
    test_write_ahead_guarantee,
    test_word_boundary,
    test_classification_order,
    test_anti_trojan,
    test_anti_trojan_runtime,
    test_synonym_removal,
    test_compound_detection,
    test_contextual_reinjection,
    test_redline_suppression,
    test_config_driven_verbs,
    test_pipeline_stage_tracking,
    test_safe_stop_inflight,
    test_event_code_taxonomy,
    test_configurable_llm_timeout,
    test_llm_response_validation,
    test_seal_review_attestation,
    test_ward_hook_enforcement,
    test_s4_personal_scope_guard,
    test_s4_scope_immutability,
    test_s4_scope_hub_validation,
    test_s4_scope_container_id,
    test_s4_archival_original_hub,
    test_s4_hard_purge,
    test_s4_governed_search,
    test_s4_ledger_pav_exclusion,
    test_s4_redline_declassification,
    test_s4_pav_hub_audit,
    test_s4_persistence_roundtrip,
    test_s4_hub_provenance,
    test_s4_provenance_persistence,
    test_s4_pipeline_integration,
    test_s5_sigil_alignment,
    test_s5_lifecycle_transitions,
    test_s5_destroyed_inaccessibility,
    test_s5_profile_immutability,
    test_s5_trace_filtering,
    test_s5_lifecycle_logging,
    test_s5_lifecycle_provenance,
    test_s5_scope_policy_tuples,
    test_s5_can_call_advisors,
    test_s5_container_persistence,
    test_s5_container_isolation,
    test_s5_s4_rules_in_containers,
    test_s5_valid_transitions_table,
    test_s5_consent_scoping,
    test_f2_entry_id_stability,
    test_f2_container_entry_id_stability,
    test_f4_event_code_registry,
    test_f4_event_categorization,
    test_f4_export_includes_summary,
    test_s6_schema_version_tracking,
    test_s6_schema_migrated_event,
    test_s6_chain_hash_migration_scaffold,
    test_s6_boot_chain_verification,
    test_s6_boot_chain_detects_tampering,
    test_s6_event_codes_registered,
    test_s6_bootstrap_event_sequence,
    test_s6_cold_verifier,
    test_a1_historical_trace_chain_loaded_on_restart,
    test_a1_boot_verification_catches_persisted_tamper,
    test_a1_unified_container_filter,
    test_a1_export_from_db_emits_chain_valid,
    test_a1_consent_persistence_roundtrip,
    test_a1_ttl_enforcement_in_stage_4,
    test_a1_post_llm_scan_covers_archive_and_ledger,
    test_c_phase_regression_battery,
    test_phase_d_regression_battery,
    test_phase_e_regression_battery,
    test_phase_e5_contextvar_isolation,
    test_adversarial_ingress,
    test_adversarial_cross_container,
    test_adversarial_scope_escalation,
    test_adversarial_audit_tamper,
    test_adversarial_malformed_inputs,
    test_adversarial_policy_confusion,
    test_domain_pack_equivalence,
    test_exception_context_leak,
    test_idempotence_replay,
    test_instructional_override,
    test_scenario_high_liability_flow,
    test_scenario_tamper_recovery,
    test_s7_amendment_ceremony,
    test_probe_chain_catches_duplicate_content_tamper,
    test_probe_redline_not_leaked_via_search_surfaces,
    test_probe_rune_resists_normalization_bypass,
    test_probe_pav_still_excludes_redline_via_list_hub,
    test_probe_indirect_prompt_injection_stays_data_not_authority,
    test_probe_untrusted_import_hash_binding,
    test_probe_hash_envelope_version_marker_present,
    test_probe_container_filter_prefix_boundary,
    test_probe_safe_stop_recovery_ceremony,
    test_oath_extended_edges,
    test_oath_input_normalization_and_handle_edges,
    test_oath_additional_proof,
    test_runtime_default_term_pack_is_config_driven,
    test_trace_export_cold_container_redline_sanitization,
    test_trace_export_extended_edges,
    test_trace_export_token_boundary_sanitization,
    test_trace_verify_cli_error_classification,
    test_trace_verify_registry_load_failure_is_nonfatal,
    test_seal_extended_edges,
    test_trace_verify_additional_proof,
    test_trace_verify_human_report_branches,
    test_trace_export_additional_proof,
    test_seal_ceremony_additional_proof,
    test_s7_amendment_persistence_roundtrip,
    test_genesis_binding_and_offline_fallback,
    test_demo_world_seed_and_container_isolation,
    test_phase_g_demo_suite_operator_flow,
    test_tecton_destructive_transitions_require_reason,
    test_clear_safe_stop_idempotence,
    test_llm_availability_timeout_is_config_driven,
    test_archive_entry_returns_hub_entry,
]


def run_all():
    _support.run_tests("RSS v0.1.0", TESTS)


if __name__ == "__main__":
    run_all()
